from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
import io

def generate_pdf_report(filename, summary):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Define a custom style for the footer since 'Small' doesn't exist by default
    small_style = ParagraphStyle(
        'SmallStyle', 
        parent=styles['Normal'], 
        fontSize=8, 
        textColor=HexColor("#666666"), 
        alignment=1  # Center aligned
    )
    
    title_style = ParagraphStyle(
        'TitleStyle', 
        parent=styles['Heading1'], 
        fontSize=22, 
        textColor=HexColor("#2563eb"), 
        spaceAfter=20
    )
    
    elements = [
        Paragraph("Summarix AI Analysis Report", title_style),
        Paragraph(f"Document: {filename}", styles['Italic']),
        Spacer(1, 12),
        HRFlowable(width="100%", thickness=1, color=HexColor("#eeeeee")),
        Spacer(1, 12),
        Paragraph("AI Generated Summary", styles['Heading2']),
        Paragraph(summary, styles['Normal']),
        Spacer(1, 40),
        # Using the new small_style we created above
        Paragraph("Generated by Summarix AI - Edge Intelligence 2026", small_style)
    ]
    
    doc.build(elements)
    buffer.seek(0)
    return buffer